encoding: UTF-8

permalink: /:year-:month-:day/:title.html
###为了使用jekyll, 去掉paginate配置
# paginate: 5
markdown: kramdown

kramdown:
  input: GFM

###为了使用jekyll, 使用rouge替代pygments, 作为语法高亮的方案
# highlighter: pygments
# pygments: true
highlighter: rouge

# 作者信息
author: 
  name: 木名
  email: mumingv@163.com
  link: http://mumingv.github.io/
  #weibo: http://weibo.com/u/2344559062
  github: https://github.com/mumingv
  github_username: mumingv 
  #weibo_username:  BladeMasterCoder

# 站点信息
title : 木名
#description: 
url: http://mumingv.github.io/
rss_url: /feed.xml

# gavatar头像及Favicon
gavatar : /assets/img/gavatar.png
favicon : /assets/img/favicon.png

# disqus 设置
#disqus:
#  shortname: blademastercoder

#profile 个人信息

profile_desc : You have to believe in yourself.<br>That is the secret of success.

# 首页除了最新文章外显示分类
cates: 
- Essay
# - Python
# - OpenStack

# 中文本地化
locals: 
   newest : 最新文章
